version: '3'

services:
  db:
    image: postgres:14.7
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  app:
    build: .
    container_name: wildfly_app
    ports:
      - "32318:32318"
      - "7203:7203"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
