FROM quay.io/wildfly/wildfly:26.1.3.Final-jdk17

ENV POSTGRES_DB studs
ENV POSTGRES_USER UNI_NUMBER
ENV POSTGRES_PASSWORD PASSWORD
ENV PORTBASE 32318
ENV JCONSOLE_PORT 32321

RUN /opt/jboss/wildfly/bin/add-user.sh admin Admin#70365 --silent

#COPY resources/standalone.xml /opt/jboss/wildfly/standalone/configuration/

#RUN /opt/jboss/wildfly/bin/standalone.sh & \
#    while ! nc -z localhost 9990; do sleep 1; done && \
#    /opt/jboss/wildfly/bin/jboss-cli.sh --connect --command="module add --name=org.postgresql --resources=/tmp/postgresql-42.3.1.jar --dependencies=javax.api,javax.transaction.api"

COPY target/interactive-graph-ui-1.0-SNAPSHOT.war /opt/jboss/wildfly/standalone/deployments/

EXPOSE $PORTBASE $JCONSOLE_PORT

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"]