CREATE SCHEMA IF NOT EXISTS UNI_NUMBER;

CREATE TABLE UNI_NUMBER.point_model
(
    id     SERIAL PRIMARY KEY,
    x      DOUBLE PRECISION NOT NULL,
    y      DOUBLE PRECISION NOT NULL,
    r      DOUBLE PRECISION NOT NULL,
    result BOOLEAN
);